# Generated by Django 3.1.1 on 2020-09-21 03:58

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(max_length=3)),
                ('food_image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/images'), upload_to='')),
            ],
        ),
    ]
