# Generated by Django 3.1.1 on 2020-09-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_edible', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='food_image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='userinput',
            name='pet_type',
            field=models.CharField(choices=[('dog', 'dog'), ('cat', 'cat')], max_length=3),
        ),
    ]
