# Generated by Django 3.1.1 on 2020-09-21 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_edible', '0002_auto_20200921_1752'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInput',
        ),
    ]
